### ISSUE TITLE
Illegal invocation on Chrome

### ISSUE THREAD

**Issue by webarthur** [jdarling/Object.observe#24]
http://jsfiddle.net/webarthur/jbmz1gso/

Object.observe(myObject, console.log);

Uncaught TypeError: Illegal invocation

**Comment by jdarling** [comment]
You can't call console.log directly in the callback.  You would have to setup a wrapper that did it for you:

```
Object.observe(myObject, function(){
  console.log.apply(console, arguments);
});
```

This isn't an issue with Object.observe, just in how you use console.log :D
